language: android
android:
  components:
    - tools
    - build-tools-21.1.2
    - android-21
    - platform-tools

script:
  - ./gradlew assembleDebug connectedCheck --stacktrace

after_script:
  - cat /home/travis/build/ameer1234567890/Cevapr/app/build/outputs/lint-results.xml

deploy:
  provider: releases
  api-key: $GITHUB_APIKEY
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
