language: android
android:
  components:
    - tools
    - build-tools-21.1.1
    - android-21
    - platform-tools
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

#script:
#  - ./gradlew build connectedCheck --stacktrace

after_script:
  - cat /home/travis/build/ameer1234567890/Cevapr/app/build/outputs/lint-results.xml

deploy:
  provider: releases
  api-key: $GITHUB_APIKEY
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
