language: android
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - platform-tools
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

sudo: false

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug --stacktrace

deploy:
  provider: releases
  api-key: $GITHUB_APIKEY
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
